name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  read_content:
    runs-on: ubuntu-latest
    steps:
      - name: Read Content
        id: read_content_step
        uses: ./.github/actions/read_content
        with:
          input1: "Resources/en.lproj/Localizable.strings"
    outputs:
      content: ${{ steps.read_content_step.outputs.content }}

  send_to_openai:
    runs-on: ubuntu-latest
    needs: read_content
    steps:
      - name: Send Data to OpenAI
        id: send_openai_step
        uses: ./.github/actions/send_to_openai
        with:
          content: "${{ needs.read_content.outputs.content }}"
          languages: |
            [
              "es",
              "fr",
              "de"
            ]
          gpt_model: "gpt-4"
          general_instruction: "Please ensure the translations are accurate and contextually appropriate."
    outputs:
      num_of_languages: ${{ steps.send_openai_step.outputs.num_of_languages }}
      tokens_count_used: ${{ steps.send_openai_step.outputs.tokens_count_used }}

  write_content:
    runs-on: ubuntu-latest
    needs: send_to_openai
    steps:
      - name: Write Content
        uses: ./.github/actions/write_content

  unit_test:
    runs-on: ubuntu-latest
    needs: write_content
    steps:
      - name: Run Unit Tests
        id: unit_test_step
        uses: ./.github/actions/unit_test
    outputs:
      test_success: ${{ steps.unit_test_step.outputs.test_success }}

  notify_slack:
    runs-on: ubuntu-latest
    needs:
      - unit_test
      - send_to_openai
    steps:
      - name: Notify Slack
        uses: ./.github/actions/notify_slack
        with:
          num_of_languages: "${{ needs.send_to_openai.outputs.num_of_languages }}"
          tokens_count_used: "${{ needs.send_to_openai.outputs.tokens_count_used }}"
          unit_test_success: "${{ needs.unit_test.outputs.test_success }}"
 