name: Main Workflow
on: [push] ##, pull_request

name: Caller Workflow

on:
  push:
 
jobs:
  ## Read data from a file
  ## And get a value back from the read_content.yml
  call_read_content:
    uses: ./.github/workflows/read_content.yml
    with:
      input1: "Localizable.strings"
    secrets: inherit
    
  ## send open ai data
  call_translate_strings:
    needs: call_read_content
    runs-on: ubuntu-latest
    uses: ./.github/workflows/send_openai.yml
    with:
      content: "${{ needs.call_read_content.outputs.content }}"
      languages: |
        [
          "es",
          "fr"
        ]
      gpt_model: "gpt-4"
      general_instruction: "Please ensure the translations are accurate and contextually appropriate."
    outputs:
      tokens_count_used: ${{ steps.get_tokens_count.outputs.tokens_count_used }}
      num_of_languages: ${{ steps.get_languages_count.outputs.num_of_languages }}

 
  ## write content to files and commit & push (array of texts) and (language_codes_array)
  process_translations:
    needs: call_translate_strings
    uses: ./.github/workflows/write_content.yml
    runs-on: ubuntu-latest
  
  ## Unit tests
  Swift_Package_CI:
    ## Run the package unit tests and get the result
    needs: process_translations
    uses: ./.github/workflows/unit_test.yml
    secrets: inherit
    outputs:
      test_success: ${{ steps.unit_test.outputs.test_success }}

  ## Notify Slack of job completion
  notify_slack:
    needs: [Swift_Package_CI, call_translate_strings]
    uses: ./.github/workflows/notify_slack.yml
    with:
      num_of_languages: "${{ needs.call_translate_strings.outputs.num_of_languages }}"
      tokens_count_used: "${{ needs.call_translate_strings.outputs.tokens_count_used }}"
      unit_test_success: ${{ needs.Swift_Package_CI.outputs.test_success }}
    secrets: inherit

 