name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  # Add other necessary permissions

jobs:
  # Job to read content from a specified file
  read_content:
    name: Read Content
    uses: ./.github/workflows/read_content.yml
    with:
      # The input file path to read
      input1: "Resources/en.lproj/Localizable.strings"

  send_to_openai:
    name: Send Data to OpenAI
    needs: read_content
    uses: ./.github/workflows/send_openai.yml
    with:
      # Content obtained from the read_content job's output
      content: "${{ needs.read_content.outputs.content }}"
      # List of target languages for translation
      languages: |
        [
          "es",
          "fr",
          "de"
        ]
      # Specify the GPT model to use for translation
      gpt_model: "gpt-4"
      # Instruction for the translation model to ensure quality
      general_instruction: "Please ensure the translations are accurate and contextually appropriate."
      # OpenAI API key (debug only, remove this to use secret from GitHub OPENAI_API_KEY)
      ## openai_api_key: "sk-proj-..."

  write_content:
    name: Write Content
    needs: send_to_openai
    uses: ./.github/workflows/write_content.yml

  unit_test:
    name: Run Unit Tests
    needs: write_content
    uses: ./.github/workflows/unit_test.yml
    ## secrets:
      ## GITHUB_TOKEN: inherit

  notify_slack:
    name: Notify Slack
    needs:
      - unit_test
      - send_to_openai
    uses: ./.github/workflows/notify_slack.yml
    with:
      # Pass the number of languages translated
      num_of_languages: "${{ needs.send_to_openai.outputs.num_of_languages }}"
      # Pass the token count used in the translation
      tokens_count_used: "${{ needs.send_to_openai.outputs.tokens_count_used }}"
      # Pass the result of the unit tests
      unit_test_success: "${{ needs.unit_test.outputs.test_success }}"
      # Slack webhook URL (debug only, remove to use variable from GitHub secret SLACK_WEBHOOK_URL)
      ## slack_webhook: "https://hooks.slack.com/services/.../..../...."

 