name: Main Workflow
on: [push] ##, pull_request

name: Caller Workflow

on:
  push:
 
jobs:
  ## Read data from a file
  ## And get a value back from the read_content.yml
  call_read_content:
    uses: ./.github/workflows/read_content.yml
    with:
      input1: "Localizable.strings"
    secrets: inherit
    
  ## send open ai data
  call_translate_strings:
    needs: call_read_content
    runs-on: ubuntu-latest
    uses: ./.github/workflows/send_openai.yml
    with:
      content: "${{ needs.call_read_content.outputs.content }}"
      languages: ["es", "fr"]
      gpt_model: "gpt-4"
      general_instruction: "Please ensure the translations are accurate and contextually appropriate."

 
  ## write content to files and commit & push (array of texts) and (language_codes_array)
  process_translations:
    needs: call_translate_strings
    uses: ./.github/workflows/write_content.yml
    runs-on: ubuntu-latest
  
  ## Unit tests
  Swift_Package_CI:
    ## run the package unit test
    uses: ./.github/workflows/unit_test.yml
    with:
      input2: ... ## no input really required
      ## we need to get the return value if the test was success or not

  ## Notify slack of job complete
  job5:
    ## pass the some tidbits to slack notifier (num_of_languages, tokens_count_used, unit_test_success)
    uses: ./.github/workflows/notify_slack.yml
    with:
      input2: ...

 