name: Main Workflow
on: [push, pull_request]

jobs:
  ## Read data from a file
  job1:
    uses: ./.github/workflows/read_content.yml
    with:
      input1: "Localizable.strings"
    ## I need to get a value back from the read_content.yml

  ## send open ai data
  job2:
    ## Send open_ai content and prompt instructions: content, languages, model to use (default is gpt4)
    uses: ./.github/workflows/send_openai.yml
    with:
      input2: ...
      ## return and use the result from openAI, json-content, and tokens_used_in_the_job
  
 
  ## write content to files and commit & push (array of texts) and (language_codes_array)
  job3:
    ## pass the value to the file writer
    uses: ./.github/workflows/write_content.yml
    with:
      input2: ...

  ## Unit tests
  job4:
    ## run the package unit test
    uses: ./.github/workflows/unit_test.yml
    with:
      input2: ... ## no input really required
      ## we need to get the return value if the test was success or not

  ## Notify slack of job complete
  job5:
    ## pass the some tidbits to slack notifier (num_of_languages, tokens_count_used, unit_test_success)
    uses: ./.github/workflows/notify_slack.yml
    with:
      input2: ...

 