## Purpose: Reads the content from the specified file (Resources/en.lproj/Localizable.strings) and outputs it for use in downstream jobs.
## Inputs and Outputs:
## - Input: input1 - the path to the file to read.
## - Output: content - the content of the file.
## Steps:
## - Checks out the repository using actions/checkout@v3.
## - Uses guibranco/github-file-reader-action-v2@latest to read the file content.
## Action Item:
## - Ensure that the file Resources/en.lproj/Localizable.strings exists in your repository and contains the strings to be localized.

## Workflow: Read Content
## Purpose: Reads the content from a specified file and outputs it for use in downstream jobs.

name: Read Content

on:
  workflow_call:
    inputs:
      input1:
        description: 'The input file path to read'
        required: true
        type: string

outputs:
  content:
    description: 'Content of the file read from the specified path'
    value: ${{ jobs.read.outputs.content }}

jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.read_output.outputs.content }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Content
        id: read_output
        run: |
          content=$(cat ${{ github.workspace }}/${{ inputs.input1 }})
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT