## Workflow: Read Content
## Purpose: Extracts content from a specified file to be used in subsequent jobs.
## Inputs:
## - `input1`: Path to the file to read (e.g., `Sources/Babel/Resources/en.lproj/Localizable.strings`).
## Outputs:
## - `content`: The retrieved content from the specified file.
## Steps:
## - Checkout the repository using `actions/checkout@v3`.
## - Read the file content using `guibranco/github-file-reader-action-v2@latest`.
## Action Item:
## - Ensure the file at the provided path exists and contains the necessary localization strings.

name: Read Content  # Define the name of the workflow

on:
  workflow_call:
    inputs:
      input1:
        description: 'The input file path to read'  # Description of the input parameter
        required: true  # Input is required
        type: string  # Input is of type string
    outputs:
      content:
        description: 'The content of the read file'  # Description of the output parameter
        value: ${{ jobs.read.outputs.content }}  # Get the output from the job 'read'

jobs:
  read:
    runs-on: ubuntu-latest  # Specify the runner environment
    outputs:
      content: ${{ steps.read_output.outputs.content }}  # Export content from the step 'read_output'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Read Content
        id: read_output
        run: |
          # Read the content of the specified file into a variable
          content=$(cat "${{ github.workspace }}/${{ inputs.input1 }}")
          # Set the output variable 'content' with the file contents
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "${content}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT