## Purpose: Runs unit tests on the new localization files to ensure they are valid.
## Verification:
## Workflow File: The unit_test.yml aims to run Swift unit tests and output the success status.

## run swift build and test for the Package.swift
## return success or failure

name: Swift Package CI

on:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

permissions:
  contents: write
