## run swift build and test for the Package.swift
## return success or failure

name: Swift Package CI

on:
  workflow_call:
    outputs:
      success:
        description: 'Whether the workflow completed successfully'
        value: ${{ jobs.build-and-test.conclusion == 'success' }}

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test