## Purpose: Runs unit tests on the new localization files to ensure they are valid.
## Verification:
## Workflow File: The unit_test.yml aims to run Swift unit tests and output the success status.

## run swift build and test for the Package.swift
## return success or failure

name: Swift Package CI

on:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Swift Packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swift-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-packages-

      - name: Build
        run: swift build -v --configuration release

      - name: Run tests
        run: swift test -v --configuration release

