## Purpose: Runs unit tests on the new localization files to ensure they are valid.
## Verification:
## Workflow File: The unit_test.yml aims to run Swift unit tests and output the success status.

## run swift build and test for the Package.swift
## return success or failure

name: Swift Package CI

on:
  workflow_call:
    outputs:
      test_success:
        description: 'Whether the unit tests succeeded'
        value: ${{ jobs.test.outputs.test_success == 'true' }}

jobs:
  test:
    runs-on: macos-latest
    outputs:
      test_success: ${{ steps.set_unit_test_success.outputs.unit_test_success }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache Swift Packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swift-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-packages-

      - name: Build
        run: swift build -v --configuration release

      - name: Run tests
        id: run_tests
        run: swift test -v --configuration release
        continue-on-error: true

      - name: Set unit_test_success
        id: set_unit_test_success
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            echo "unit_test_success=true" >> $GITHUB_OUTPUT
          else
            echo "unit_test_success=false" >> $GITHUB_OUTPUT
          fi

