## Purpose: Writes the translated content to the appropriate localization files.
## Workflow File: The write_content.yml downloads the translations artifact and runs a Node.js script to create localization files.
## Script Used: scripts/write_localizations.js
## 1. Accept JSON input.
## 2. Convert JSON to the desired format.
## 3. Write each item's content to files named Localization-{{language_code}}.strings.
## 4. Commit and push the changes.
name: Write Content

on:
  workflow_call:

permissions:
  contents: write  # Grants write permission to push changes

jobs:
  write_content_job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the translations artifact from previous workflow
      - name: Download translations artifact
        uses: actions/download-artifact@v3
        with:
          name: translations
          path: ./artifacts

      # Note: The artifact is automatically extracted. No need for manual extraction.

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Updated to the latest LTS version

      # Step 4: Create localization files using the extracted translations
      - name: Create localization files
        run: |
          node scripts/write_localizations.js ./artifacts/translations.json

      # Step 5: Configure Git with user information
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 6: Commit and Push changes
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update localization files via GitHub Actions'
          branch: main
          file_pattern: 'Sources/Babel/Resources/**'


          