## 1. Accept JSON input.
## 2. Convert JSON to the desired format.
## 3. Write each item's content to files named Localization-{{language_code}}.strings.
## 4. Commit and push the changes.
name: Write Content

on:
  workflow_call:
    secrets: inherit

jobs:
  generate_localizations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download translations artifact
        uses: actions/download-artifact@v3
        with:
          name: translations
          path: ./artifacts

      - name: Extract translations
        if: ${{ runner.os != 'Windows' }}
        run: |
          tar -xzf ./artifacts/translations.tar.gz -C ./artifacts
        shell: bash

      - name: Extract translations (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          tar -xzf .\artifacts\translations.tar.gz -C .\artifacts
        shell: powershell

      - name: Create localization files
        run: |
          node scripts/write_localizations.js ./artifacts/translations.json

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update localization files via GitHub Actions'
          branch: main
          file_pattern: 'Localization-*.strings'